name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - name: build
      run: ./sw build source -static
    #- name: test
      #run: ./sw test source
    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: sw-windows
        path: .sw/out

  linux:
    runs-on: ubuntu-20.04
    container: fedora:36
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo dnf -y update
        sudo dnf -y install flex bison cmake which gcc clang clang-tools-extra lld git \
            lttng-tools-devel lttng-ust-devel libproxy-devel mesa-libGL-devel mesa-libEGL-devel \
            libXfixes-devel libXtst-devel libXext-devel libXrender-devel libX11-devel pulseaudio-libs-devel \
            cups-devel wayland-devel libxkbcommon-devel libXdamage-devel libXrandr-devel
    - uses: egorpugin/sw-action@master
    - run: ./sw -static build source -compiler gcc
    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: sw-linux
        path: .sw/out

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - name: install
      run: brew install flex bison gcc
    - name: build
      run: |
        export PATH="/usr/local/opt/flex/bin:$PATH"
        export PATH="/usr/local/opt/bison/bin:$PATH"
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        ./sw -static build source
    - uses: actions/upload-artifact@v1
      with:
        name: sw
        path: .sw/out
